[profile.default]
solc_version = '0.8.27'
evm_version = 'cancun'
optimizer = true
optimizer-runs = 200
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
cache_path = 'cache'

[fuzz]
runs = 256

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
